# 基本配置
title: 刘小刚的小站
author: xiaogangliu
description: 个人网站

# Jekyll 主题配置
remote_theme: pages-themes/cayman@v0.2.0

# 插件配置
plugins:
  - jekyll-remote-theme
  - jekyll-feed

# Cayman 主题特定配置
cayman:
  theme: default  # 可选: default, dark, solarized, solarized-dark
  layout: default

# 社交媒体链接
social:
  github: xiaogangliu

# 构建设置
markdown: kramdown
